BEGIN TRANSACTION;
CREATE TABLE possessions (owner TEXT, item TEXT, qty INTEGER, timestamp INTEGER);
INSERT INTO "possessions" VALUES('esh','titanium',100,1256198422);
INSERT INTO "possessions" VALUES('esh','titanium',-20,1256198430);
INSERT INTO "possessions" VALUES('esh','tungsten',30,1256198447);
INSERT INTO "possessions" VALUES('yuki','tungsten',60,1256198460);
CREATE TABLE items (name TEXT, description TEXT);
INSERT INTO "items" VALUES('titanium','');
INSERT INTO "items" VALUES('tungsten','');
INSERT INTO "items" VALUES('uranium','');
INSERT INTO "items" VALUES('hydrogen','');
CREATE TABLE ship_types (name TEXT, attack INTEGER, defense INTEGER, shields INTEGER, description TEXT);
INSERT INTO "ship_types" VALUES('ark ship',1,1,1,'');
INSERT INTO "ship_types" VALUES('frigate',1,1,1,'');
INSERT INTO "ship_types" VALUES('cruiser',1,1,1,'');
CREATE TABLE resources (x INTEGER, y INTEGER, owner TEXT, item TEXT, yield INTEGER);
INSERT INTO "resources" VALUES(0,0,NULL,'titanium',1);
INSERT INTO "resources" VALUES(1,0,NULL,'titanium',1);
INSERT INTO "resources" VALUES(2,1,'esh','titanium',1);
INSERT INTO "resources" VALUES(2,1,'esh','tungsten',1);
CREATE TABLE ships (x INTEGER, y INTEGER, owner TEXT, ship_type TEXT, shields REAL);
INSERT INTO "ships" VALUES(2,1,'esh','ark ship',1.0);
INSERT INTO "ships" VALUES(1,0,'esh','frigate',1.0);
COMMIT;
